# Generated by Django 4.0 on 2022-02-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
