# Generated by Django 4.0 on 2022-02-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_alter_accounts_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='balance',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
